### ISSUE TITLE
Documenting TitanicSurvivalPrediction

### ISSUE THREAD

**Issue by A91y** [A91y/simple-ml#4]
Write documentation for TitanicSurvivalPrediction model, explaining each and every aspect of model and it's working!

**Comment by Sherwin-14** [comment]
Is someone working on this issue?

**Comment by A91y** [comment]
>  Is someone working on this issue?

As of now, no one is assigned this issue. You are welcome to contribute your efforts to address and resolve it!

**Comment by Sherwin-14** [comment]
Ok. should i use docstrings in code or use a documentation generator?

**Comment by A91y** [comment]
> Ok. should i use docstrings in code or use a documentation generator?

You have the choice to utilize docstrings within your code or opt for a documentation generator, as long as you fulfill the expectations of creating a separate README.md file.

**Comment by Sherwin-14** [comment]
README.md file. Sorry i didn't understand this. do i need to make a readme.md as well?

**Comment by A91y** [comment]
> README.md file. Sorry i didn't understand this. do i need to make a readme.md as well?

Apologies for the unclear issue statement, the main resolution is to create a README.md file in the directory of TitanicSurvivalPrediction, documenting it right there.

Creating docstring or anything else is optional and just an add-on.

**Comment by Sherwin-14** [comment]
I'd like to take this issue up then.

**Comment by A91y** [comment]
> I'd like to take this issue up then.

Go ahead Sherwin!
